# https://docs.docker.com/compose/compose-file
version: "3.9"

services:
 postgres-hotel:
  image: postgres:alpine
  restart: on-failure
  env_file: docker/.env.postgres-hotel
  volumes:
   - ./dbdata/postgresql/hotel:/var/lib/postgresql/data
  ports:
   - 5432:5432

 redis-hotel:
  image: redis/redis-stack-server:latest
  ports:
   - 6379:6379

 prometheus-hotel:
  image: prom/prometheus
  volumes:
   - ./dbdata/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
   - 9090:9090

 grafana-hotel:
   image: grafana/grafana:latest
   container_name: grafana
   ports:
    - 3000:3000
   environment:
    - GF_SECURITY_ADMIN_PASSWORD=passw0rd
   volumes:
    - ./dbdata/grafana_data:/var/lib/grafana
